export const API_URL = ' https://api.spotify.com/v1/'

export const FETCH_ALL_ARTISTS_SUCCEEDED = 'FETCH_ALL_ARTISTS_SUCCEEDED'
export const FETCH_ALL_ARTISTS_REQUESTED = 'FETCH_ALL_ARTISTS_REQUESTED'
export const FETCH_ALL_ARTISTS_FAILED = 'FETCH_ALL_ARTISTS_FAILED'
