export const API_URL = ' https://api.spotify.com/v1/'

export const FETCH_ALL_ARTISTS_SUCCEEDED = 'FETCH_ALL_ARTISTS_SUCCEEDED'
export const FETCH_ALL_ARTISTS_REQUESTED = 'FETCH_ALL_ARTISTS_REQUESTED'
export const FETCH_ALL_ARTISTS_FAILED = 'FETCH_ALL_ARTISTS_FAILED'

export const FETCH_USER_SUCCEEDED = 'FETCH_USER_SUCCEEDED'
export const FETCH_USER_REQUESTED = 'FETCH_USER_REQUESTED'
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED'

export const FETCH_CURRENT_USER_ALBUMS_FAILED = 'FETCH_CURRENT_USER_ALBUMS_FAILED'
export const FETCH_CURRENT_USER_ALBUMS_REQUESTED = 'FETCH_CURRENT_USER_ALBUMS_REQUESTED'
export const FETCH_CURRENT_USER_ALBUMS_SUCCEEDED = 'FETCH_CURRENT_USER_ALBUMS_SUCCEEDED'

export const FETCH_NEW_ALBUMS_FAILED = 'FETCH_NEW_ALBUMS_FAILED'
export const FETCH_NEW_ALBUMS_REQUESTED = 'FETCH_NEW_ALBUMS_REQUESTED'
export const FETCH_NEW_ALBUMS_SUCCEEDED = 'FETCH_NEW_ALBUMS_SUCCEEDED'

export const REMOVE_CURRENT_USER_ALBUMS_FAILED = 'REMOVE_CURRENT_USER_ALBUMS_FAILED'
export const REMOVE_CURRENT_USER_ALBUMS_REQUESTED = 'REMOVE_CURRENT_USER_ALBUMS_REQUESTED'
export const REMOVE_CURRENT_USER_ALBUMS_SUCCEEDED = 'REMOVE_CURRENT_USER_ALBUMS_SUCCEEDED'

export const SAVE_CURRENT_USER_ALBUMS_FAILED = 'SAVE_CURRENT_USER_ALBUMS_FAILED'
export const SAVE_CURRENT_USER_ALBUMS_REQUESTED = 'SAVE_CURRENT_USER_ALBUMS_REQUESTED'
export const SAVE_CURRENT_USER_ALBUMS_SUCCEEDED = 'SAVE_CURRENT_USER_ALBUMS_SUCCEEDED'

export const FETCH_CURRENT_USER_TRACKS_FAILED = 'FETCH_CURRENT_USER_TRACKS_FAILED'
export const FETCH_CURRENT_USER_TRACKS_REQUESTED = 'FETCH_CURRENT_USER_TRACKS_REQUESTED'
export const FETCH_CURRENT_USER_TRACKS_SUCCEEDED = 'FETCH_CURRENT_USER_TRACKS_SUCCEEDED'

export const REMOVE_CURRENT_USER_TRACKS_FAILED = 'REMOVE_CURRENT_USER_TRACKS_FAILED'
export const REMOVE_CURRENT_USER_TRACKS_REQUESTED = 'REMOVE_CURRENT_USER_TRACKS_REQUESTED'
export const REMOVE_CURRENT_USER_TRACKS_SUCCEEDED = 'REMOVE_CURRENT_USER_TRACKS_SUCCEEDED'

export const SAVE_CURRENT_USER_TRACKS_FAILED = 'SAVE_CURRENT_USER_TRACKS_FAILED'
export const SAVE_CURRENT_USER_TRACKS_REQUESTED = 'SAVE_CURRENT_USER_TRACKS_REQUESTED'
export const SAVE_CURRENT_USER_TRACKS_SUCCEEDED = 'SAVE_CURRENT_USER_TRACKS_SUCCEEDED'

export const AUTHORIZE_USER_SUCCEEDED = 'AUTHORIZE_USER_SUCCEEDED'
export const AUTHORIZE_USER_REQUESTED = 'AUTHORIZE_USER_REQUESTED'
export const AUTHORIZE_USER_FAILED = 'AUTHORIZE_USER_FAILED'

export const FETCH_FEATURED_PLAYLISTS_FAILED = 'FETCH_FEATURED_PLAYLISTS_FAILED'
export const FETCH_FEATURED_PLAYLISTS_REQUESTED = 'FETCH_FEATURED_PLAYLISTS_REQUESTED'
export const FETCH_FEATURED_PLAYLISTS_SUCCEEDED = 'FETCH_FEATURED_PLAYLISTS_SUCCEEDED'
